language: node_js

node_js:
  - "0.12"
  - "0.11"

sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.4.2

before_install:
  docker build -t no0dles/pigeon-registry-server .
  docker run no0dles/pigeon-registry-server /bin/sh -c "npm test"

install:
  - npm install

script:
  - npm test

after_success:

after_failure:

before_deploy:

deploy:

after_deploy:

after_script:

notifications:
  email: false